<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Kaff.E2E.Tests</RootNamespace>
    <AssemblyName>Kaff.E2E.Tests</AssemblyName>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

</Project>
