// <auto-generated />
using System;
using Kaff.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kaff.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KaffDbContext))]
    partial class KaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kaff.Domain.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_role");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("ChangedProperties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_properties");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("GrantPath")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("grant_path");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("request_path");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_records_actor");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_records_correlation");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_records_occurred_at");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_audit_records_project");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_records_entity");

                    b.ToTable("audit_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_records_event_shape", "(action = 'Occurred') = (event_type IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_records_grant_path", "grant_path IS NULL OR (project_id IS NOT NULL AND grant_path <> 'None')");

                            t.HasCheckConstraint("ck_audit_records_has_state", "event_type IS NOT NULL OR before_json IS NOT NULL OR after_json IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.Identity.ProjectAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("level");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_assignments_active")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("UserId", "ProjectId")
                        .HasDatabaseName("ix_project_assignments_user_project");

                    b.ToTable("project_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_assignments_revocation_complete", "(revoked_at IS NULL AND revoked_by_user_id IS NULL) OR (revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Department")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int>("FailedSignInAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_sign_in_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LockedOutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_out_until");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<string>("OperationsSubDepartment")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operations_sub_department");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneEntered")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_entered");

                    b.Property<string>("PhoneNormalised")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_normalised");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PhoneNormalised")
                        .HasDatabaseName("ix_users_phone_normalised");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_user_name");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_client_scope", "(role = 'Client' AND client_id IS NOT NULL) OR (role <> 'Client' AND client_id IS NULL)");

                            t.HasCheckConstraint("ck_users_operations_sub_department", "(department = 'Operations' AND operations_sub_department IS NOT NULL) OR (department IS DISTINCT FROM 'Operations' AND operations_sub_department IS NULL)");

                            t.HasCheckConstraint("ck_users_subcontractor_cannot_log_in", "role <> 'Subcontractor' OR password_hash IS NULL");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.Bab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<decimal>("DefaultMarkup")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("default_markup");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<Guid?>("ParentBabId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_bab_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_babs_code");

                    b.HasIndex("ParentBabId");

                    b.ToTable("babs", null, t =>
                        {
                            t.HasCheckConstraint("ck_babs_not_own_parent", "parent_bab_id IS NULL OR parent_bab_id <> id");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.CatalogueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BabId")
                        .HasColumnType("uuid")
                        .HasColumnName("bab_id");

                    b.Property<decimal>("BaseSellRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("base_sell_rate");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_price");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_en");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("BabId")
                        .HasDatabaseName("ix_catalogue_items_bab");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_catalogue_items_code");

                    b.ToTable("catalogue_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalogue_items_cost_not_negative", "cost_price >= 0");

                            t.HasCheckConstraint("ck_catalogue_items_rate_not_negative", "base_sell_rate >= 0");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("address");

                    b.Property<string>("AlternatePhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("alternate_phone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneEntered")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_entered");

                    b.Property<string>("PhoneNormalised")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_normalised");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_registration_number");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_code");

                    b.HasIndex("PhoneNormalised")
                        .HasDatabaseName("ix_clients_phone");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BabId")
                        .HasColumnType("uuid")
                        .HasColumnName("bab_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateOnly?>("HiredOn")
                        .HasColumnType("date")
                        .HasColumnName("hired_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_title");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("NationalId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("national_id");

                    b.Property<string>("PhoneEntered")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_entered");

                    b.Property<string>("PhoneNormalised")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_normalised");

                    b.Property<string>("Specialty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("specialty");

                    b.HasKey("Id");

                    b.HasIndex("BabId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_code");

                    b.HasIndex("PhoneNormalised")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_phone");

                    b.ToTable("employees", null, t =>
                        {
                            t.HasCheckConstraint("ck_employees_day_labour_has_trade", "kind <> 'DayLabour' OR bab_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.Subcontractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneEntered")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_entered");

                    b.Property<string>("PhoneNormalised")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_normalised");

                    b.Property<decimal>("RetentionRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("retention_rate");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_registration_number");

                    b.Property<Guid?>("TradeBabId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_bab_id");

                    b.Property<string>("WithholdingCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("withholding_category");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_subcontractors_code");

                    b.HasIndex("PhoneNormalised")
                        .IsUnique()
                        .HasDatabaseName("ux_subcontractors_phone");

                    b.HasIndex("TradeBabId");

                    b.ToTable("subcontractors", (string)null);
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneEntered")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_entered");

                    b.Property<string>("PhoneNormalised")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_normalised");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_registration_number");

                    b.Property<string>("WithholdingCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("withholding_category");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_suppliers_code");

                    b.HasIndex("PhoneNormalised")
                        .IsUnique()
                        .HasDatabaseName("ux_suppliers_phone");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Kaff.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AdvanceRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("advance_rate");

                    b.Property<decimal?>("AdvanceRecoveryRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("advance_recovery_rate");

                    b.Property<decimal?>("AreaSquareMetres")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("area_square_metres");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("contract_type");

                    b.Property<decimal?>("ContractValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("contract_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("currency");

                    b.Property<bool>("DelayPenaltyEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("delay_penalty_enabled");

                    b.Property<decimal?>("DesignRatePerSquareMetre")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("design_rate_per_square_metre");

                    b.Property<DateOnly?>("HandoverOn")
                        .HasColumnType("date")
                        .HasColumnName("handover_on");

                    b.Property<decimal?>("HoldRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("hold_rate");

                    b.Property<string>("LinkType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("link_type");

                    b.Property<Guid?>("LinkedProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_project_id");

                    b.Property<decimal?>("MaterialAdvanceRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("material_advance_rate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<DateOnly?>("SignedOn")
                        .HasColumnType("date")
                        .HasColumnName("signed_on");

                    b.Property<DateOnly?>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("StoppageReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("stoppage_reason");

                    b.Property<DateOnly?>("StoppedOn")
                        .HasColumnType("date")
                        .HasColumnName("stopped_on");

                    b.Property<decimal?>("SupervisionRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("supervision_rate");

                    b.Property<DateOnly?>("TerminatedOn")
                        .HasColumnType("date")
                        .HasColumnName("terminated_on");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("termination_reason");

                    b.Property<DateOnly?>("WarrantyEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("warranty_ends_on");

                    b.Property<string>("WithholdingCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("withholding_category");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_projects_client");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_code");

                    b.HasIndex("LinkedProjectId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_area_positive", "area_square_metres IS NULL OR area_square_metres > 0");

                            t.HasCheckConstraint("ck_projects_cost_plus_terms", "contract_type = 'CostPlus' OR supervision_rate IS NULL");

                            t.HasCheckConstraint("ck_projects_design_terms", "contract_type = 'Design' OR (area_square_metres IS NULL AND design_rate_per_square_metre IS NULL)");

                            t.HasCheckConstraint("ck_projects_link_complete", "(linked_project_id IS NULL AND link_type IS NULL) OR (linked_project_id IS NOT NULL AND link_type IS NOT NULL)");

                            t.HasCheckConstraint("ck_projects_lump_sum_terms", "contract_type = 'LumpSum' OR (advance_rate IS NULL AND hold_rate IS NULL AND advance_recovery_rate IS NULL AND material_advance_rate IS NULL)");

                            t.HasCheckConstraint("ck_projects_not_linked_to_itself", "linked_project_id IS NULL OR linked_project_id <> id");

                            t.HasCheckConstraint("ck_projects_stoppage_reason", "stopped_on IS NULL OR stoppage_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_projects_termination_reason", "terminated_on IS NULL OR termination_reason IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.Sales.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClosedLostReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("closed_lost_reason");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Guid?>("ConvertedProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_opportunities_client");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_opportunities_code");

                    b.HasIndex("Status", "LastActivityAt")
                        .HasDatabaseName("ix_opportunities_activity");

                    b.ToTable("opportunities", null, t =>
                        {
                            t.HasCheckConstraint("ck_opportunities_closed_lost_reason", "status <> 'ClosedLost' OR closed_lost_reason IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.Treasury.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("class");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("currency");

                    b.Property<bool>("EnforceNonNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("enforce_non_negative");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<string>("LedgerKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ledger_kind");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normal_balance");

                    b.Property<DateOnly>("OpenedOn")
                        .HasColumnType("date")
                        .HasColumnName("opened_on");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_account_id");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("PartyType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("party_type");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_code");

                    b.HasIndex("LedgerKind")
                        .HasDatabaseName("ix_accounts_ledger_kind");

                    b.HasIndex("ParentAccountId");

                    b.HasIndex("PartyType", "PartyId")
                        .HasDatabaseName("ix_accounts_party");

                    b.HasIndex("ProjectId", "Type")
                        .HasDatabaseName("ix_accounts_project_type");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_closed_after_opened", "closed_on IS NULL OR closed_on >= opened_on");

                            t.HasCheckConstraint("ck_accounts_ledger_is_postable", "ledger_kind IS NULL OR is_postable = TRUE");

                            t.HasCheckConstraint("ck_accounts_party_complete", "(party_type IS NULL AND party_id IS NULL) OR (party_type IS NOT NULL AND party_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.Treasury.AccountBalance", b =>
                {
                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("account_code");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("class");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Inflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("inflow");

                    b.Property<DateOnly?>("LastPostingDate")
                        .HasColumnType("date")
                        .HasColumnName("last_posting_date");

                    b.Property<string>("LedgerKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ledger_kind");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normal_balance");

                    b.Property<decimal>("Outflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("outflow");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("PartyType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("party_type");

                    b.Property<int>("PostingCount")
                        .HasColumnType("integer")
                        .HasColumnName("posting_count");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("RawBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("raw_balance");

                    b.Property<decimal>("SignedBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("signed_balance");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.ToTable((string)null);

                    b.ToView("account_balances", (string)null);
                });

            modelBuilder.Entity("Kaff.Domain.Treasury.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ux_accounting_periods_year_month");

                    b.HasIndex("Status", "StartsOn", "EndsOn")
                        .HasDatabaseName("ix_accounting_periods_status_range");

                    b.ToTable("accounting_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounting_periods_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_accounting_periods_range", "ends_on >= starts_on");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.Treasury.Posting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("FromAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_account_id");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date")
                        .HasColumnName("posting_date");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("ReversesId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_id");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<string>("SourceDocumentReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_document_reference");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_document_type");

                    b.Property<Guid>("ToAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_account_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ReversesId")
                        .IsUnique()
                        .HasDatabaseName("ux_postings_reverses")
                        .HasFilter("reverses_id IS NOT NULL");

                    b.HasIndex("FromAccountId", "PostingDate")
                        .HasDatabaseName("ix_postings_from_account_date");

                    b.HasIndex("ProjectId", "PostingDate")
                        .HasDatabaseName("ix_postings_project_date");

                    b.HasIndex("SourceDocumentType", "SourceDocumentId")
                        .HasDatabaseName("ix_postings_source_document");

                    b.HasIndex("ToAccountId", "PostingDate")
                        .HasDatabaseName("ix_postings_to_account_date");

                    b.ToTable("postings", null, t =>
                        {
                            t.HasCheckConstraint("ck_postings_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_postings_distinct_accounts", "from_account_id <> to_account_id");

                            t.HasCheckConstraint("ck_postings_not_self_reversing", "reverses_id IS NULL OR reverses_id <> id");
                        });
                });

            modelBuilder.Entity("Kaff.Domain.Identity.ProjectAssignment", b =>
                {
                    b.HasOne("Kaff.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kaff.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kaff.Domain.Identity.User", b =>
                {
                    b.HasOne("Kaff.Domain.MasterData.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kaff.Domain.MasterData.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.Bab", b =>
                {
                    b.HasOne("Kaff.Domain.MasterData.Bab", null)
                        .WithMany()
                        .HasForeignKey("ParentBabId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.CatalogueItem", b =>
                {
                    b.HasOne("Kaff.Domain.MasterData.Bab", null)
                        .WithMany()
                        .HasForeignKey("BabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.Employee", b =>
                {
                    b.HasOne("Kaff.Domain.MasterData.Bab", null)
                        .WithMany()
                        .HasForeignKey("BabId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kaff.Domain.MasterData.Subcontractor", b =>
                {
                    b.HasOne("Kaff.Domain.MasterData.Bab", null)
                        .WithMany()
                        .HasForeignKey("TradeBabId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kaff.Domain.Projects.Project", b =>
                {
                    b.HasOne("Kaff.Domain.MasterData.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kaff.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("LinkedProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kaff.Domain.Sales.Opportunity", null)
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kaff.Domain.Sales.Opportunity", b =>
                {
                    b.HasOne("Kaff.Domain.MasterData.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kaff.Domain.Treasury.Account", b =>
                {
                    b.HasOne("Kaff.Domain.Treasury.Account", null)
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kaff.Domain.Treasury.Posting", b =>
                {
                    b.HasOne("Kaff.Domain.Treasury.Account", null)
                        .WithMany()
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kaff.Domain.Treasury.Posting", null)
                        .WithMany()
                        .HasForeignKey("ReversesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kaff.Domain.Treasury.Account", null)
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
