# Regenerates the GENERATED block of STATUS.md from the `<!-- kaff ... -->` trailers in
# stories/**/KAFF-*.md, plus git. Everything outside the markers is hand-maintained and is
# left untouched.
#
#     pwsh -NoProfile -File tools/status.ps1          # rewrite STATUS.md
#     pwsh -NoProfile -File tools/status.ps1 -Check   # exit 1 if it is stale (CI / pre-push)
#
# A story with no trailer is reported as UNKNOWN rather than omitted: an unmaintained row
# has to be visible, because a missing row reads as "nothing to do".
[CmdletBinding()]
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$statusFile = Join-Path $root 'STATUS.md'
$BEGIN = '<!-- BEGIN GENERATED - tools/status.ps1 - do not edit by hand -->'
$END = '<!-- END GENERATED -->'

$stories = Get-ChildItem (Join-Path $root 'stories') -Recurse -Filter 'KAFF-*.md' | ForEach-Object {
    $line = Select-String -Path $_.FullName -Pattern '^<!-- kaff (.+) -->$' | Select-Object -First 1
    $r = [ordered]@{ id = ($_.BaseName -replace '^(KAFF-\d+[a-z]?).*', '$1'); slice = '?'
        points = 0; state = 'UNKNOWN'; verdict = 'none'; at = '-'; on = '-'; file = $_.Name
    }
    if ($line) {
        foreach ($kv in ($line.Matches[0].Groups[1].Value -split '\s+')) {
            $k, $v = $kv -split '=', 2
            if ($r.Contains($k)) { $r[$k] = $v }
        }
        $r.points = [int]$r.points
    }
    # The title, so STATUS.md never needs a second hand-kept list of what a story is.
    $r.title = ((Get-Content $_.FullName -TotalCount 1 -Encoding UTF8) -replace '^#\s*KAFF-\d+[a-z]?\s*\W+\s*', '').Trim()
    [pscustomobject]$r
} | Sort-Object { $_.id -replace '\D', '' -as [int] }, id

# LIVE = a state that counts as work standing today. SUPERSEDED/FOLDED are neither done nor owed.
$live = $stories | Where-Object { $_.state -notin 'SUPERSEDED', 'FOLDED' }
$sum = { param($p) $s = ($live | Where-Object $p | Measure-Object points -Sum).Sum; if ($null -eq $s) { 0 } else { $s } }

$verified = & $sum { $_.state -eq 'VERIFIED' -and $_.verdict -in 'PASS', 'CONDITIONAL' }
$lapsed = & $sum { $_.verdict -eq 'LAPSED' }
$built = & $sum { $_.state -in 'BUILT', 'DELIVERED' }
$ready = & $sum { $_.state -in 'READY', 'COMMITTED' }
$accepted = & $sum { $_.state -eq 'ACCEPTED' }
$unknown = & $sum { $_.state -eq 'UNKNOWN' }
$total = & $sum { $true }

$head = (git -C $root rev-parse --short HEAD).Trim()
$dirty = if ((git -C $root status --porcelain)) { ' · ⚠️ working tree DIRTY' } else { ' · tree clean' }

$b = [System.Text.StringBuilder]::new()
$null = $b.AppendLine($BEGIN)
$null = $b.AppendLine("*Generated by ``tools/status.ps1`` from the ``<!-- kaff -->`` trailers. **Edit a story file, then re-run** — hand edits here are overwritten.*")
$null = $b.AppendLine()
$null = $b.AppendLine("**HEAD** ``$head``$dirty")
$null = $b.AppendLine()
$null = $b.AppendLine('## Points, slice 1')
$null = $b.AppendLine()
$null = $b.AppendLine('| | pts |')
$null = $b.AppendLine('|---|---:|')
$null = $b.AppendLine("| ✅ **ACCEPTED** — Nabil ran the demo script (``process/agile.md`` §4) | **$accepted** |")
$null = $b.AppendLine("| 🔵 VERIFIED — a Verifier gave a verdict, and it still stands | $verified |")
$null = $b.AppendLine("| ⛔ LAPSED — had a verdict; later code moved under it (D-096) | $lapsed |")
$null = $b.AppendLine("| 🟡 BUILT — shipped, nobody independent has looked | $built |")
$null = $b.AppendLine("| ⚪ READY / COMMITTED — not built | $ready |")
if ($unknown) { $null = $b.AppendLine("| ❓ UNKNOWN — story file carries no trailer | $unknown |") }
$null = $b.AppendLine("| | **$total in slice 1** |")
$null = $b.AppendLine()
$null = $b.AppendLine('## Every story')
$null = $b.AppendLine()
$null = $b.AppendLine('| Story | Pts | State | Verdict | At | On | |')
$null = $b.AppendLine('|---|---:|---|---|---|---|---|')
foreach ($s in $stories) {
    $mark = switch ($s.state) {
        'ACCEPTED' { '✅' } 'VERIFIED' { if ($s.verdict -eq 'LAPSED') { '⛔' } elseif ($s.verdict -eq 'CONDITIONAL') { '🔶' } else { '🔵' } }
        'BUILT' { '🟡' } 'DELIVERED' { '🟡' } 'UNKNOWN' { '❓' } default { '⚪' }
    }
    $null = $b.AppendLine("| [$($s.id)](stories/slice-1-foundation/$($s.file)) | $($s.points) | $mark $($s.state) | $($s.verdict) | ``$($s.at)`` | $($s.on) | $($s.title) |")
}
$null = $b.AppendLine()
$null = $b.AppendLine($END)
$generated = $b.ToString().Replace("`r`n", "`n").TrimEnd() + "`n"

$current = if (Test-Path $statusFile) { (Get-Content $statusFile -Raw -Encoding UTF8).Replace("`r`n", "`n") } else { '' }
$pattern = "(?s)" + [regex]::Escape($BEGIN) + ".*?" + [regex]::Escape($END) + "\r?\n?"
if ($current -notmatch [regex]::Escape($BEGIN)) { throw "STATUS.md has no generated block. Add:`n$BEGIN`n$END" }
$updated = [regex]::Replace($current, $pattern, { $generated })

if ($Check) {
    if ($updated -ne $current) { Write-Error 'STATUS.md is stale. Run: pwsh -NoProfile -File tools/status.ps1'; exit 1 }
    'STATUS.md is current.'; exit 0
}
[System.IO.File]::WriteAllText($statusFile, $updated)
"STATUS.md written - $total pts in slice 1, $accepted accepted, $verified verified, $lapsed lapsed, $built built, $ready ready."
