# Regenerates the GENERATED block of STATUS.md from the `<!-- kaff ... -->` trailers in
# stories/**/KAFF-*.md, plus git. Everything outside the markers is hand-maintained and is
# left untouched.
#
#     pwsh -NoProfile -File tools/status.ps1          # rewrite STATUS.md
#     pwsh -NoProfile -File tools/status.ps1 -Check   # exit 1 if it is stale (CI / pre-push)
#
# A story with no trailer is reported as UNKNOWN rather than omitted: an unmaintained row
# has to be visible, because a missing row reads as "nothing to do".
[CmdletBinding()]
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$statusFile = Join-Path $root 'STATUS.md'
$BEGIN = '<!-- BEGIN GENERATED - tools/status.ps1 - do not edit by hand -->'
$END = '<!-- END GENERATED -->'

$stories = Get-ChildItem (Join-Path $root 'stories') -Recurse -Filter 'KAFF-*.md' | ForEach-Object {
    $line = Select-String -Path $_.FullName -Pattern '^<!-- kaff (.+) -->$' | Select-Object -First 1
    # path is the real location, not an assumed folder: slice 3 lives outside slice-1-foundation/.
    $r = [ordered]@{ id = ($_.BaseName -replace '^(KAFF-\d+[a-z]?).*', '$1'); slice = '?'
        points = 0; state = 'UNKNOWN'; verdict = 'none'; at = '-'; on = '-'
        path = $_.FullName.Substring($root.Length + 1).Replace('\', '/')
    }
    if ($line) {
        foreach ($kv in ($line.Matches[0].Groups[1].Value -split '\s+')) {
            $k, $v = $kv -split '=', 2
            if ($r.Contains($k)) { $r[$k] = $v }
        }
        $r.points = [int]$r.points
    }
    # The title, so STATUS.md never needs a second hand-kept list of what a story is.
    $r.title = ((Get-Content $_.FullName -TotalCount 1 -Encoding UTF8) -replace '^#\s*KAFF-\d+[a-z]?\s*\W+\s*', '').Trim()
    [pscustomobject]$r
} | Sort-Object { $_.id -replace '\D', '' -as [int] }, id

# LIVE = a state that counts as work standing today. SUPERSEDED/FOLDED are neither done nor owed.
$live = $stories | Where-Object { $_.state -notin 'SUPERSEDED', 'FOLDED' }
# Every bucket is scoped to one slice: summing slices together reports a number for no real thing.
$sum = { param($sl, $p) $s = ($live | Where-Object { $_.slice -eq $sl } | Where-Object $p | Measure-Object points -Sum).Sum; if ($null -eq $s) { 0 } else { $s } }
$slices = $live.slice | Sort-Object -Unique

# Rows are (label, predicate). ACCEPTED first because it is the number that has never moved.
$buckets = @(
    @('✅ **ACCEPTED** — Nabil ran the demo script (`process/agile.md` §4)', { $_.state -eq 'ACCEPTED' }),
    @('🔵 VERIFIED — a Verifier gave a verdict, and it still stands', { $_.state -eq 'VERIFIED' -and $_.verdict -in 'PASS', 'CONDITIONAL' }),
    @('⛔ LAPSED — had a verdict; later code moved under it (D-096)', { $_.verdict -eq 'LAPSED' }),
    @('🟡 BUILT — shipped, nobody independent has looked', { $_.state -in 'BUILT', 'DELIVERED' }),
    @('⚪ READY / COMMITTED — refined, not built', { $_.state -in 'READY', 'COMMITTED' }),
    @('⚫ NOT-BUILT — cut, and not yet Ready', { $_.state -eq 'NOT-BUILT' }),
    @('🔻 DEFERRED — carried out of this slice, to a named place', { $_.state -eq 'DEFERRED' }),
    @('❓ UNKNOWN — story file carries no trailer', { $_.state -eq 'UNKNOWN' })
)

# ⛔ The generated block contains ONLY facts derived from the trailers.
# It used to print HEAD and the dirty flag. Both are self-invalidating: regenerating writes the
# current sha, and committing that write moves HEAD past it, so -Check exited 1 on every clean
# committed tree. A gate that can never be green is a gate people learn to ignore. Git state is
# read from git, at the moment it is needed, by whoever needs it.

$b = [System.Text.StringBuilder]::new()
$null = $b.AppendLine($BEGIN)
$null = $b.AppendLine("*Generated by ``tools/status.ps1`` from the ``<!-- kaff -->`` trailers. **Edit a story file, then re-run** — hand edits here are overwritten.*")
$null = $b.AppendLine()
$null = $b.AppendLine('## Points by slice')
$null = $b.AppendLine()
$null = $b.AppendLine("| | $(($slices | ForEach-Object { "slice $_" }) -join ' | ') |")
$null = $b.AppendLine("|---|$('---:|' * $slices.Count)")
foreach ($bk in $buckets) {
    $cells = $slices | ForEach-Object { & $sum $_ $bk[1] }
    # A bucket empty in every slice is noise; ACCEPTED stays regardless, because zero is the finding.
    if (($cells | Measure-Object -Sum).Sum -eq 0 -and $bk[0] -notmatch 'ACCEPTED') { continue }
    $null = $b.AppendLine("| $($bk[0]) | $($cells -join ' | ') |")
}
$null = $b.AppendLine("| **total** | $(($slices | ForEach-Object { "**$(& $sum $_ { $true })**" }) -join ' | ') |")
$null = $b.AppendLine()
$null = $b.AppendLine('## Every story')
$null = $b.AppendLine()
$null = $b.AppendLine('| Story | Slice | Pts | State | Verdict | At | On | |')
$null = $b.AppendLine('|---|---:|---:|---|---|---|---|---|')
foreach ($s in $stories) {
    $mark = switch ($s.state) {
        'ACCEPTED' { '✅' } 'VERIFIED' { if ($s.verdict -eq 'LAPSED') { '⛔' } elseif ($s.verdict -eq 'CONDITIONAL') { '🔶' } else { '🔵' } }
        'BUILT' { '🟡' } 'DELIVERED' { '🟡' } 'NOT-BUILT' { '⚫' } 'DEFERRED' { '🔻' } 'UNKNOWN' { '❓' } default { '⚪' }
    }
    $null = $b.AppendLine("| [$($s.id)]($($s.path)) | $($s.slice) | $($s.points) | $mark $($s.state) | $($s.verdict) | ``$($s.at)`` | $($s.on) | $($s.title) |")
}
$null = $b.AppendLine()
$null = $b.AppendLine($END)
$generated = $b.ToString().Replace("`r`n", "`n").TrimEnd() + "`n"

$current = if (Test-Path $statusFile) { (Get-Content $statusFile -Raw -Encoding UTF8).Replace("`r`n", "`n") } else { '' }
$pattern = "(?s)" + [regex]::Escape($BEGIN) + ".*?" + [regex]::Escape($END) + "\r?\n?"
if ($current -notmatch [regex]::Escape($BEGIN)) { throw "STATUS.md has no generated block. Add:`n$BEGIN`n$END" }
$updated = [regex]::Replace($current, $pattern, { $generated })

if ($Check) {
    if ($updated -ne $current) { Write-Error 'STATUS.md is stale. Run: pwsh -NoProfile -File tools/status.ps1'; exit 1 }
    'STATUS.md is current.'; exit 0
}
[System.IO.File]::WriteAllText($statusFile, $updated)
$report = $slices | ForEach-Object {
    "slice ${_}: $(& $sum $_ { $true }) pts, $(& $sum $_ { $_.state -eq 'ACCEPTED' }) accepted"
}
"STATUS.md written - " + ($report -join ' | ')
